### ISSUE TITLE
Fix bug: products from transactions being added to database again

### ISSUE THREAD

**Issue by KBonnicksen** [KBonnicksen/MiniPosSystem#24]
After completing the entire process of putting together an order, submitting payment and completing a transaction, all of the products that were in the transaction are being put into the database again. The products, in turn, are appearing multiple times on the order form page.

![Capture](https://user-images.githubusercontent.com/44908223/62333978-9a585200-b47a-11e9-9a9b-9e8865f6020d.PNG)

**Comment by Kevin11Stone** [comment]
@KBonnicksen 
Does it not look like because the transactions property "Products" is a List<>, Entity Framework didn't create a column for it within the table?
I read the following from going to the definition of the add() method we always use to add an object to the database. 

    // Remarks:
    //     Note that DbSet does not support MEST (Multiple Entity Sets per Type) meaning
    //     that there is always a one-to-one correlation between a type and a set.

**Comment by Kevin11Stone** [comment]
The previous remark wasn't commented above the method but the class

**Comment by KBonnicksen** [comment]
Oh you're right! We need to set up their relationships.

**Comment by KBonnicksen** [comment]
Database was ignoring the ID's of products and adding new ID's to them (creating new objects in the database). This is the default setting. The issue was fixed in TransactionsDB.AddTransaction(). Notes are included.
